### ISSUE TITLE
Set Up Project Dependencies

### ISSUE THREAD

**Issue by DevindaWanasinghe** [DevindaWanasinghe/food-delivery_webProject-frontend#2]
- Install necessary dependencies for the project.
- Tasks:

- [x] Install React Router
- [x] Install Redux and Redux Toolkit
- [x] Install Axios for HTTP requests
- [x] Install Other all dependencies

Commit and push changes to GitHub

**Comment by IsharaWanninayaka** [comment]
"dependencies": {
    "@react-oauth/google": "^0.12.1",
    "@reduxjs/toolkit": "^2.2.7",
    "axios": "^1.7.4",
    "googleapis": "^140.0.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-icons": "^5.3.0",
    "react-router-dom": "^6.26.0"
  }
